# Generated by: python -m ops.scripts.core.derived_surfaces
# Source of truth: ops/policies/derived-surfaces.json
# Regenerate with: make derived-surfaces-sync
.PHONY: _internal-sync-derived _internal-sync-derived-check

_internal-sync-derived:
	$(MAKE) pytest-markers-sync
	$(MAKE) test-selectors-sync
	$(MAKE) sync-public-policy
	$(MAKE) workflow-action-pins-sync
	$(MAKE) script-output-surfaces
	$(MAKE) script-lifecycle-policy
	$(MAKE) script-module-surfaces
	$(MAKE) release-governance-sync
	$(MAKE) release-workflow-order-guard-spec-sync
	$(MAKE) release-workflow-order-guard
	$(MAKE) make-target-inventory

_internal-sync-derived-check:
	$(MAKE) pytest-markers-sync-check
	$(MAKE) test-selectors-sync-check
	$(MAKE) sync-public-policy-check
	$(MAKE) workflow-action-pins-sync-check
	$(MAKE) script-output-surfaces-check
	$(MAKE) script-lifecycle-policy-check
	$(MAKE) script-module-surfaces-check
	$(MAKE) release-governance-sync-check
	$(MAKE) release-workflow-order-guard-spec-sync-check
	$(MAKE) release-workflow-order-guard-check
	$(MAKE) make-target-inventory-check
