REVIEW_ARCHIVE_OUT ?= build/review/llm-wiki-vnext-review.zip
REVIEW_ARCHIVE_REPORT_OUT ?= ops/reports/review-archive-report.json
REVIEW_ARCHIVE_PROFILE ?= clean
EXTERNAL_REPORT_REFERENCE_MANIFEST_OUT ?= external-reports/report-reference-manifest.json
EXTERNAL_REPORT_REFERENCE_MANIFEST_MODE ?= advisory
EXTERNAL_REPORT_REVIEW_BASIS_ZIP_NAME ?=
EXTERNAL_REPORT_REVIEW_BASIS_ZIP_SHA256 ?=
EXTERNAL_REPORT_REVIEW_BASIS_ZIP_ENTRY_COUNT ?=
EXTERNAL_REPORT_REVIEW_BASIS_ZIP_PATH ?=
EXTERNAL_REPORT_BASIS_ZIP_NAME ?=
EXTERNAL_REPORT_BASIS_ZIP_SHA256 ?=
EXTERNAL_REPORT_BASIS_ZIP_ENTRY_COUNT ?=
EXTERNAL_REPORT_BASIS_ZIP_PATH ?=
EXTERNAL_REPORT_EFFECTIVE_REVIEW_BASIS_ZIP_NAME = $(if $(EXTERNAL_REPORT_REVIEW_BASIS_ZIP_NAME),$(EXTERNAL_REPORT_REVIEW_BASIS_ZIP_NAME),$(EXTERNAL_REPORT_BASIS_ZIP_NAME))
EXTERNAL_REPORT_EFFECTIVE_REVIEW_BASIS_ZIP_SHA256 = $(if $(EXTERNAL_REPORT_REVIEW_BASIS_ZIP_SHA256),$(EXTERNAL_REPORT_REVIEW_BASIS_ZIP_SHA256),$(EXTERNAL_REPORT_BASIS_ZIP_SHA256))
EXTERNAL_REPORT_EFFECTIVE_REVIEW_BASIS_ZIP_ENTRY_COUNT = $(if $(EXTERNAL_REPORT_REVIEW_BASIS_ZIP_ENTRY_COUNT),$(EXTERNAL_REPORT_REVIEW_BASIS_ZIP_ENTRY_COUNT),$(EXTERNAL_REPORT_BASIS_ZIP_ENTRY_COUNT))
EXTERNAL_REPORT_EFFECTIVE_REVIEW_BASIS_ZIP_PATH = $(if $(EXTERNAL_REPORT_REVIEW_BASIS_ZIP_PATH),$(EXTERNAL_REPORT_REVIEW_BASIS_ZIP_PATH),$(EXTERNAL_REPORT_BASIS_ZIP_PATH))
EXTERNAL_REPORT_CURRENT_DISTRIBUTION_ZIP_NAME ?=
EXTERNAL_REPORT_CURRENT_DISTRIBUTION_ZIP_SHA256 ?=
EXTERNAL_REPORT_CURRENT_DISTRIBUTION_ZIP_ENTRY_COUNT ?=
EXTERNAL_REPORT_CURRENT_DISTRIBUTION_ZIP_PATH ?=
EXTERNAL_REPORT_ACTION_MATRIX_OUT ?= ops/reports/external-report-action-matrix.json
GITHUB_GOVERNANCE_LIVE_INPUT ?= build/release/github-governance-live-input.json
GITHUB_GOVERNANCE_LIVE_DRIFT_OUT ?= ops/reports/github-governance-live-drift.json
GITHUB_GOVERNANCE_LIVE_DRIFT_CHECK_OUT ?= tmp/github-governance-live-drift-check.json
FRESHNESS_OWNER_ROUTE_CONVERGE_PLAN_OUT ?= tmp/freshness-owner-route-converge-plan.json
RELEASE_SMOKE_OUT ?= ops/reports/release-smoke-report.json
RELEASE_SMOKE_FAST_OUT ?= ops/reports/release-smoke-report-fast.json
RELEASE_SMOKE_ARCHIVE_OUT ?= build/release/release-smoke.zip
RELEASE_SMOKE_FAST_ARCHIVE_OUT ?= build/release/release-smoke-fast.zip
RELEASE_SMOKE_REUSE_FROM ?= $(RELEASE_SMOKE_OUT)
RELEASE_SMOKE_CURRENT_CHECK_OUT ?= tmp/release-smoke-report-current-check.json
RELEASE_SMOKE_FAST_CURRENT_CHECK_OUT ?= tmp/release-smoke-report-fast-current-check.json
RELEASE_SOURCE_READY_COMMIT_MESSAGE ?= release: converge source-ready surfaces
RELEASE_SOURCE_READY_PRE_STATUS_OUT ?= tmp/release-source-ready-pre-status.json
RELEASE_SOURCE_READY_COMMIT_OUT ?= tmp/release-source-ready-commit.json
RELEASE_SOURCE_READY_STATUS_OUT ?= tmp/release-source-ready-status.json
RELEASE_WORKTREE_CLEAN_CHECK_OUT ?= tmp/release-worktree-clean-check.json
RELEASE_POST_COMMIT_FINALIZATION_OUT ?= build/release/release-post-commit-finalization.json
RELEASE_POST_COMMIT_FINALIZATION_SNAPSHOT_OUT ?= tmp/release-post-commit-finalization.snapshot.json
RELEASE_RUN_MANIFEST_OUT ?= build/release/release-run-manifest.json
RELEASE_RUN_READY_PLAN_OUT ?= build/release/release-run-ready-plan.json
RELEASE_RUN_READY_PLAN_CHECK_OUT ?= tmp/release-run-ready-plan-check.json
RELEASE_SEALED_RUN_MANIFEST_OUT ?= build/release/release-sealed-run-manifest.json
RELEASE_AUTO_PROMOTION_READY_MANIFEST_OUT ?= build/release/release-auto-promotion-ready-manifest.json
RELEASE_AUTHORITY_INVENTORY_OUT ?= tmp/release-authority-inventory.json
RELEASE_AUTO_PROMOTION_PREFLIGHT_OUT ?= build/release/release-auto-promotion-preflight.json
RELEASE_AUTO_PROMOTION_PRESEAL_OUT ?= build/release/release-auto-promotion-preseal.json
RELEASE_AUTO_PROMOTION_GOAL_RUN_IDENTITY_OUT ?= build/release/release-auto-promotion-goal-run-identity.json
RELEASE_SEALED_RUN_READY_PLAN_OUT ?= build/release/release-sealed-run-ready-plan.json
RELEASE_AUTO_PROMOTION_READY_PLAN_OUT ?= build/release/release-auto-promotion-ready-plan.json
RELEASE_AUTO_PROMOTION_OPERATOR_SUMMARY_OUT ?= $(RELEASE_CLOSEOUT_SEALED_OPERATOR_SUMMARY_OUT)
RELEASE_SEALED_POST_SEAL_ATTESTATION_OUT ?= build/release/release-sealed-post-seal-attestation.json
RELEASE_RUN_READY_MAKE_BIN ?= make
RELEASE_RUN_READY_TIMEOUT_SECONDS ?= 7200
SOURCE_PACKAGE_SMOKE_ROOT ?= build/source-package-smoke
SOURCE_PACKAGE_SMOKE_OUT ?= $(SOURCE_PACKAGE_SMOKE_ROOT)/source-package-smoke.json
SOURCE_PACKAGE_SMOKE_EXTRACT_PARENT ?= $(SOURCE_PACKAGE_SMOKE_ROOT)/extract
SOURCE_PACKAGE_SMOKE_PYTHON ?= $(PUBLIC_PYTHON)
SOURCE_PACKAGE_CLEAN_EXTRACT_OUT ?= ops/reports/source-package-clean-extract.json
SOURCE_PACKAGE_CLEAN_EXTRACT_ROOT ?= tmp/source-package-clean-extract
SOURCE_PACKAGE_CLEAN_EXTRACT_EXTRACT_PARENT ?= $(SOURCE_PACKAGE_CLEAN_EXTRACT_ROOT)/extract
SOURCE_PACKAGE_CLEAN_EXTRACT_TEST_SUMMARY_OUT ?= tmp/source-package-clean-extract/test-execution-summary.json
SOURCE_PACKAGE_CLEAN_EXTRACT_DESELECTION_POLICY ?= ops/policies/report-contract-deselections.json
SOURCE_PACKAGE_CLEAN_EXTRACT_PYTEST_MARK_EXPR ?= not release_sealing
SOURCE_PACKAGE_CLEAN_EXTRACT_TESTS ?= tests/test_release_run_manifest.py tests/test_source_tree_fingerprint_runtime.py
SOURCE_PACKAGE_CLEAN_EXTRACT_DESELECTS ?=
SOURCE_PACKAGE_CLEAN_EXTRACT_PYTEST_FLAGS ?= -q
RELEASE_CLOSEOUT_SUMMARY_OUT ?= ops/reports/release-closeout-summary.json
RELEASE_CLOSEOUT_SUMMARY_CANDIDATE_OUT ?= tmp/release-closeout-summary.candidate.json
RELEASE_CLEAN_LANE_EVIDENCE_REVIEW_OUT ?= tmp/release-clean-lane-evidence-review.json
RELEASE_EVIDENCE_DASHBOARD_OUT ?= ops/reports/release-evidence-dashboard.json
RELEASE_EVIDENCE_DASHBOARD_CANDIDATE_OUT ?= tmp/release-evidence-dashboard.candidate.json
RELEASE_EVIDENCE_COHORT_OUT ?= ops/reports/release-evidence-cohort.json
RELEASE_EVIDENCE_COHORT_STAGING_OUT ?= tmp/release-evidence-cohort.candidate.json
RELEASE_EVIDENCE_COHORT_DIAGNOSTIC_OUT ?= tmp/release-evidence-cohort-check.json
RELEASE_CLOSEOUT_BATCH_MANIFEST_OUT ?= ops/reports/release-closeout-batch-manifest.json
RELEASE_CLOSEOUT_BATCH_MANIFEST_CANDIDATE_OUT ?= tmp/release-closeout-batch-manifest.candidate.json
RELEASE_CLOSEOUT_BATCH_MANIFEST_ZIP_METADATA ?=
RELEASE_CLOSEOUT_DISTRIBUTION_ZIP ?=
RELEASE_CLOSEOUT_BATCH_MANIFEST_ZIP_TIMESTAMP_TIMEZONE ?= UTC
RELEASE_CLOSEOUT_FIXED_POINT_OUT ?= ops/reports/release-closeout-fixed-point.json
RELEASE_CLOSEOUT_FIXED_POINT_CANDIDATE_OUT ?= tmp/release-closeout-fixed-point.candidate.json
RELEASE_CLOSEOUT_POST_CHECK_FINALIZER_OUT ?= tmp/release-closeout-post-check-finalizer.json
RELEASE_CLOSEOUT_POST_CHECK_FINALIZER_RECOMMENDED_TARGETS_OUT ?= tmp/release-closeout-post-check-finalizer-recommended-targets.txt
RELEASE_CLOSEOUT_POST_CHECK_FINALIZER_PLAN_OUT ?= tmp/release-closeout-post-check-finalizer-plan.json
RELEASE_CLOSEOUT_POST_CHECK_FINALIZER_FLAGS ?=
RELEASE_CLOSEOUT_FIXED_POINT_COST_TREND_OUT ?= ops/reports/release-closeout-fixed-point-cost-trend.json
RELEASE_CLOSEOUT_FIXED_POINT_COST_TREND_CANDIDATE_OUT ?= tmp/release-closeout-fixed-point-cost-trend.candidate.json
RELEASE_CLOSEOUT_FIXED_POINT_TIMEOUT_SECONDS ?= 600
RELEASE_CLOSEOUT_FIXED_POINT_INITIAL_TARGETS ?=
OPERATOR_EVIDENCE_FINALITY_INITIAL_TARGETS ?= generated-artifact-index-body-current-or-refresh artifact-freshness external-report-action-matrix release-closeout-summary-report learning-readiness-signoff-revalidation release-evidence-cohort release-evidence-dashboard-report release-lane-summary release-clean-blocker-ledger release-closeout-batch-manifest-promote release-evidence-closeout-self-check
OPERATOR_EVIDENCE_ARTIFACT_FRESHNESS_PROGRESS ?= jsonl-stable
RELEASE_CLOSEOUT_FINALITY_ATTESTATION_OUT ?= ops/reports/release-closeout-finality-attestation.json
RELEASE_CLOSEOUT_FINALITY_ATTESTATION_CANDIDATE_OUT ?= tmp/release-closeout-finality-attestation.candidate.json
RELEASE_DISTRIBUTION_ZIP_OUT ?= build/release/LLMwiki-source.zip
RELEASE_DISTRIBUTION_ZIP_SMOKE_OUT ?= build/release/release-distribution-zip-smoke.json
RELEASE_CLOSEOUT_SEALED_DISTRIBUTION_ZIP ?= $(if $(RELEASE_CLOSEOUT_DISTRIBUTION_ZIP),$(RELEASE_CLOSEOUT_DISTRIBUTION_ZIP),$(RELEASE_DISTRIBUTION_ZIP_OUT))
RELEASE_CLOSEOUT_SEALED_ZIP_METADATA ?= $(if $(RELEASE_CLOSEOUT_BATCH_MANIFEST_ZIP_METADATA),$(RELEASE_CLOSEOUT_BATCH_MANIFEST_ZIP_METADATA),$(RELEASE_CLOSEOUT_SEALED_DISTRIBUTION_ZIP))
RELEASE_AUTO_PROMOTION_EFFECTIVE_DISTRIBUTION_ZIP = $(strip $(RELEASE_CLOSEOUT_SEALED_DISTRIBUTION_ZIP))
RELEASE_AUTO_PROMOTION_EFFECTIVE_ZIP_METADATA = $(strip $(if $(RELEASE_CLOSEOUT_BATCH_MANIFEST_ZIP_METADATA),$(RELEASE_CLOSEOUT_BATCH_MANIFEST_ZIP_METADATA),$(RELEASE_AUTO_PROMOTION_EFFECTIVE_DISTRIBUTION_ZIP)))
RELEASE_CLOSEOUT_SEALED_REHEARSAL_CHECK_OUT ?= build/release/release-closeout-sealed-rehearsal-check.json
RELEASE_CLOSEOUT_SEALED_REHEARSAL_CHECK_CANONICAL_OUT ?= ops/reports/release-closeout-sealed-rehearsal-check.json
RELEASE_CLOSEOUT_SEALED_REHEARSAL_CHECK_RELEASE_OUT ?= build/release/release-closeout-sealed-rehearsal-check.json
RELEASE_CLOSEOUT_SEALED_REHEARSAL_CHECK_BATCH_MANIFEST ?= build/release/release-closeout-batch-manifest.json
RELEASE_CLOSEOUT_SEALED_REHEARSAL_CHECK_EXTERNAL_MANIFEST ?= build/release/external-report-reference-manifest.json
RELEASE_CLOSEOUT_SEALED_EXTERNAL_MANIFEST_OUT ?= build/release/external-report-reference-manifest.json
RELEASE_CLOSEOUT_SEALED_BATCH_MANIFEST_OUT ?= build/release/release-closeout-batch-manifest.json
RELEASE_CLOSEOUT_SEALED_SELF_CHECK_OUT ?= build/release/release-evidence-closeout-self-check.json
RELEASE_CLOSEOUT_SEALED_OPERATOR_SUMMARY_OUT ?= build/release/operator-release-summary.json
RELEASE_CLOSEOUT_SEALED_DRY_RUN_ROOT ?= build/release/release-closeout-sealed-dry-run
RELEASE_CLOSEOUT_SEALED_DRY_RUN_DISTRIBUTION_ZIP ?= $(RELEASE_CLOSEOUT_SEALED_DRY_RUN_ROOT)/LLMwiki-source.zip
RELEASE_CLOSEOUT_SEALED_DRY_RUN_SMOKE_OUT ?= $(RELEASE_CLOSEOUT_SEALED_DRY_RUN_ROOT)/release-distribution-zip-smoke.json
RELEASE_CLOSEOUT_SEALED_DRY_RUN_EXTERNAL_MANIFEST_OUT ?= $(RELEASE_CLOSEOUT_SEALED_DRY_RUN_ROOT)/external-report-reference-manifest.json
RELEASE_CLOSEOUT_SEALED_DRY_RUN_BATCH_MANIFEST_OUT ?= $(RELEASE_CLOSEOUT_SEALED_DRY_RUN_ROOT)/release-closeout-batch-manifest.json
RELEASE_CLOSEOUT_SEALED_DRY_RUN_CHECK_OUT ?= $(RELEASE_CLOSEOUT_SEALED_DRY_RUN_ROOT)/release-closeout-sealed-rehearsal-check.json
RELEASE_CLOSEOUT_SEALED_DRY_RUN_CHECK_FLAGS ?= --no-fail
RELEASE_EVIDENCE_CLOSEOUT_SELF_CHECK_OUT ?= ops/reports/release-evidence-closeout-self-check.json
RELEASE_AUDIT_PACK_OUT ?= build/release/release-audit-pack.zip
RELEASE_AUDIT_PACK_INCLUDE_OPTIONAL_PAYLOADS ?=
RELEASE_POST_SEAL_ATTESTATION_OUT ?= build/release/release-post-seal-attestation.json
RELEASE_POST_SEAL_ATTESTATION_SOURCE_ZIP ?= $(RELEASE_CLOSEOUT_SEALED_DISTRIBUTION_ZIP)
RELEASE_POST_SEAL_ATTESTATION_BATCH_MANIFEST ?=
RELEASE_POST_SEAL_ATTESTATION_SELF_CHECK ?=
RELEASE_POST_SEAL_ATTESTATION_OPERATOR_SUMMARY ?=
RELEASE_LANE_SUMMARY_OUT ?= ops/reports/release-lane-summary.json
RELEASE_LANE_SUMMARY_CANDIDATE_OUT ?= tmp/release-lane-summary.candidate.json
RELEASE_CLEAN_BLOCKER_LEDGER_OUT ?= ops/reports/release-clean-blocker-ledger.json
RELEASE_CLEAN_BLOCKER_LEDGER_CANDIDATE_OUT ?= tmp/release-clean-blocker-ledger.candidate.json
OPERATOR_RELEASE_SUMMARY_OUT ?= ops/operator/operator-release-summary.json
RELEASE_CLOSEOUT_PROFILE ?= base
RELEASE_EVIDENCE_COHORT_POLICY ?= allowed_divergence_with_explicit_risk
RELEASE_EVIDENCE_COHORT_PROVENANCE_MODE ?= embedded_currentness
RELEASE_EVIDENCE_COHORT_ZIP_METADATA ?=
LEARNING_READINESS_SIGNOFF_OUT ?= ops/reports/learning-readiness-signoff.json
LEARNING_READINESS_SIGNOFF_REUSE_FROM ?= $(LEARNING_READINESS_SIGNOFF_OUT)
LEARNING_READINESS_SIGNOFF_ACCEPTED_BY ?=
LEARNING_READINESS_SIGNOFF_EXPIRY_DAYS ?= 14
LEARNING_READINESS_SIGNOFF_RISK_OWNER ?= runtime-maintainer
LEARNING_READINESS_SIGNOFF_REVALIDATION_CONDITION ?= Rerun make release-evidence-closeout and inspect learning readiness metrics before release.
LEARNING_READINESS_SIGNOFF_ROLLBACK_TRIGGER ?= Treat learning_blocked_by_review_required as active again if release evidence changes, learning telemetry regresses, or this signoff expires.
LEARNING_READINESS_SIGNOFF_NOTES ?=
LEARNING_READINESS_SIGNOFF_REVALIDATION_OUT ?= ops/reports/learning-readiness-signoff-revalidation.json
LEARNING_READINESS_SIGNOFF_REVALIDATION_CHECK_OUT ?= tmp/learning-readiness-signoff-revalidation-check.json
LEARNING_READINESS_SIGNOFF_REVALIDATION_WINDOW_DAYS ?= 7
LEARNING_READINESS_SIGNOFF_REVALIDATION_COMMAND ?= make release-evidence-converge PYTHON=.venv/bin/python
LEARNING_READINESS_SIGNOFF_REVALIDATION_ENVIRONMENT ?= .venv clean release-builder
LEARNING_CLAIM_EVIDENCE_BUNDLE_OUT ?= ops/reports/learning-claim-evidence-bundle.json
LEARNING_CLAIM_EVIDENCE_BUNDLE_CANDIDATE_OUT ?= tmp/learning-claim-evidence-bundle.candidate.json
LEARNING_CONFIRMED_LEGACY_RECONSTRUCTION_OUT ?= ops/reports/learning-confirmed-legacy-reconstruction.json
LEARNING_CONFIRMED_LEGACY_RECONSTRUCTION_CANDIDATE_OUT ?= tmp/learning-confirmed-legacy-reconstruction.candidate.json
LEARNING_CONFIRMED_EVIDENCE_COHORT_OUT ?= ops/reports/learning-confirmed-evidence-cohort.json
LEARNING_CONFIRMED_EVIDENCE_COHORT_CANDIDATE_OUT ?= tmp/learning-confirmed-evidence-cohort.candidate.json
LEARNING_CLAIM_UNLOCK_REVIEW_OUT ?= ops/reports/learning-claim-unlock-review.json
LEARNING_CLAIM_UNLOCK_REVIEW_CANDIDATE_OUT ?= tmp/learning-claim-unlock-review.candidate.json
LEARNING_CLAIM_AUTO_UNLOCK_POLICY ?= ops/policies/learning-claim-auto-unlock.json
LEARNING_CLAIM_CONFIRMED_IMPROVEMENT_POLICY ?= ops/policies/learning-claim-confirmed-improvement.json
LEARNING_CLAIM_UNLOCK_REVIEW_APPROVED_BY ?=
LEARNING_CLAIM_UNLOCK_REVIEW_REVIEWED_AT ?=
LEARNING_DELTA_SCOREBOARD_OUT ?= ops/reports/learning-delta-scoreboard.json
LEARNING_DELTA_SCOREBOARD_CANDIDATE_OUT ?= tmp/learning-delta-scoreboard.candidate.json
LEARNING_CLAIM_ACTIVATION_REPORT_OUT ?= ops/reports/learning_claim_activation_report.json
LEARNING_CLAIM_ACTIVATION_REPORT_CANDIDATE_OUT ?= tmp/learning-claim-activation-report.candidate.json
SESSION_SYNOPSIS_OUT ?= ops/reports/session-synopsis.json
SESSION_SYNOPSIS_CANDIDATE_OUT ?= tmp/session-synopsis.candidate.json
SELF_IMPROVEMENT_NEGATIVE_LESSONS_OUT ?= ops/reports/self-improvement-negative-lessons.json
SELF_IMPROVEMENT_NEGATIVE_LESSONS_CANDIDATE_OUT ?= tmp/self-improvement-negative-lessons.candidate.json
REMEDIATION_BACKLOG_OUT ?= ops/reports/remediation-backlog.json
REMEDIATION_BACKLOG_CANDIDATE_OUT ?= tmp/remediation-backlog.candidate.json


include mk/release-authority.mk
include mk/release-evidence.mk
include mk/release-learning.mk
