#!/usr/bin/env python3
from __future__ import annotations

from typing import Any

ROADMAP_SOURCE_ONLY_ACTION_IDS = {
    "public_mirror_boundary_helper",
    "lint_uplift_plan_full_scope",
    "type_uplift_plan_full_scope",
    "mechanism_navigation_index",
    "cli_surface_inventory",
    "tools_migration_plan",
    "release_authority_inventory",
    "observation_closeout_lint",
    "subagent_profile_schema",
    "ci_tier_lane_bridge",
    "compatibility_alias_deprecation",
    "public_surface_snapshot",
    "doc_graph_integrity_lint",
}

SOURCE_REVISION_RELEASE_AUTHORITY_REPORTS = {
    "ops/reports/learning-readiness-signoff.json",
    "ops/reports/release-closeout-batch-manifest.json",
    "ops/reports/release-closeout-finality-attestation.json",
    "ops/reports/release-closeout-fixed-point.json",
    "ops/reports/release-closeout-sealed-rehearsal-check.json",
    "ops/reports/release-evidence-closeout-self-check.json",
    "ops/reports/review-archive-report.json",
    "ops/reports/source-package-clean-extract.json",
    "ops/reports/test-execution-summary-full.json",
}

ACTION_CATALOG: list[dict[str, Any]] = [
    {
        "action_id": "script_output_surfaces_currentness",
        "priority": "P0",
        "theme": "writer output surface currentness",
        "patterns": [r"script-output-surfaces", r"writer/output surface", r"writer output"],
        "evidence_paths": ["ops/script-output-surfaces.json"],
        "recommended_target": "script-output-surfaces",
    },
    {
        "action_id": "release_writer_dependency_single_source",
        "priority": "P0",
        "theme": "release writer ordering single source",
        "patterns": [r"workflow_dependency_planner", r"fixed-point", r"writer dependency", r"single source"],
        "evidence_paths": [
            "ops/reports/workflow-dependency-planner.json",
            "ops/reports/release-workflow-order-guard.json",
        ],
        "recommended_target": "release-workflow-order-guard",
    },
    {
        "action_id": "function_budget_proposal_adapter",
        "priority": "P1",
        "theme": "wiki_lint function-budget triage",
        "patterns": [r"function-budget", r"wiki_lint review", r"review candidate"],
        "evidence_paths": ["ops/reports/function-budget-refactor-proposals.json"],
        "recommended_target": "function-budget-refactor-proposals",
    },
    {
        "action_id": "windows_path_and_archive_alias_parity",
        "priority": "P1",
        "theme": "path portability and archive alias normalization",
        "patterns": [r"Windows", r"path alias", r"path portability", r"Info-ZIP", r"C locale", r"escaped path"],
        "evidence_paths": [
            "tests/test_raw_registry_preflight.py",
            "tests/test_raw_registry_cross_environment_matrix.py",
            "tests/test_raw_registry_cross_environment_evidence_bundle.py",
            "tests/test_release_smoke.py",
            "tests/test_ci_workflow_static.py",
        ],
        "recommended_target": "test-public",
    },
    {
        "action_id": "outcome_provenance_gate_policy",
        "priority": "P2",
        "theme": "outcome/provenance policy escalation",
        "patterns": [r"outcome", r"provenance", r"same-eval", r"rollback rehearsal", r"promotion gate"],
        "evidence_paths": ["ops/reports/outcome-provenance-gate-policy.json"],
        "recommended_target": "outcome-provenance-gate-policy",
    },
    {
        "action_id": "external_report_lifecycle",
        "priority": "P1",
        "theme": "active external report lifecycle",
        "patterns": [r"external report lifecycle", r"active external", r"report-reference-manifest", r"active report set"],
        "evidence_paths": [
            "external-reports/report-reference-manifest.json",
            "ops/reports/external-report-action-matrix.json",
        ],
        "recommended_target": "external-report-action-matrix",
    },
    {
        "action_id": "operator_only_external_report_binary",
        "priority": "P1",
        "theme": "binary active external report operator review",
        "patterns": [r"binary external report", r"PDF", r"DOCX", r"operator-only"],
        "evidence_paths": [],
        "recommended_target": "external-report-reference-manifest-settle",
    },
    {
        "action_id": "active_report_manifest_freshness",
        "priority": "P0",
        "theme": "active external report manifest freshness",
        "patterns": [
            r"active reference set",
            r"missing active report",
            r"report-reference-manifest",
            r"active report set",
            r"active external report",
        ],
        "evidence_paths": [
            "external-reports/report-reference-manifest.json",
            "ops/reports/external-report-action-matrix.json",
        ],
        "recommended_target": "external-report-reference-manifest-settle",
    },
    {
        "action_id": "source_revision_unknown_canonical_reports",
        "priority": "P0",
        "theme": "canonical report source revision provenance",
        "patterns": [
            r"source_revision\s*[:=]\s*unknown",
            r"source_revision",
            r"source revision",
            r"Git revision",
            r"source_package_without_git",
            r"canonical report.*unknown",
        ],
        "evidence_paths": [
            "ops/scripts/core/source_revision_runtime.py",
            "ops/scripts/core/artifact_freshness_runtime.py",
            "ops/scripts/core/bootstrap_preflight.py",
            "tests/test_source_revision_runtime.py",
            "ops/reports/artifact-freshness-report.json",
        ],
        "recommended_target": "artifact-freshness-refresh-check",
    },
    {
        "action_id": "ruff_strict_preview_import_order",
        "priority": "P0",
        "theme": "Ruff strict preview import-order currentness",
        "patterns": [
            r"Ruff strict",
            r"\bI001\b",
            r"import order",
            r"ruff-strict-preview",
        ],
        "evidence_paths": [
            "ops/scripts/mechanism/auto_improve_iteration_persistence_runtime.py",
            "tools/ruff_strict_preview.py",
            "mk/static.mk",
        ],
        "recommended_target": "ruff-strict-preview",
    },
    {
        "action_id": "release_source_ready_deindex_hardening",
        "priority": "P0",
        "theme": "release source-ready local-only deindex hardening",
        "patterns": [
            r"release_source_ready_commit",
            r"release-source-ready",
            r"deindex",
            r"local-only private",
            r"git add -u",
        ],
        "evidence_paths": [
            "ops/scripts/release/release_source_ready_commit.py",
            "tests/test_release_source_ready_commit.py",
        ],
        "recommended_target": "release-source-ready-commit",
    },
    {
        "action_id": "uv_lock_canonical_policy",
        "priority": "P1",
        "theme": "uv lock canonical dependency policy",
        "patterns": [
            r"uv lock --check",
            r"uv\.lock",
            r"lockfile",
            r"canonical dependency",
        ],
        "evidence_paths": [
            "pyproject.toml",
            "uv.lock",
            "docs/development.md",
        ],
        "recommended_target": "uv-lock-check",
    },
    {
        "action_id": "operator_entrypoint_index",
        "priority": "P1",
        "theme": "operator Make entrypoint index",
        "patterns": [
            r"operator entrypoint",
            r"operator index",
            r"make help",
            r"release/public/mechanism/report-contract",
        ],
        "evidence_paths": [
            "Makefile",
            "mk/core.mk",
            "docs/development.md",
        ],
        "recommended_target": "help",
    },
    {
        "action_id": "strict_preview_all_target_audit",
        "priority": "P1",
        "theme": "strict-preview all-target audit after legacy allowlist removal",
        "patterns": [
            r"strict-preview",
            r"allowlist",
            r"all-target",
            r"all target",
            r"ops/scripts tests tools",
        ],
        "evidence_paths": [
            "tools/strict_preview_audit.py",
            "mk/static.mk",
            "tests/test_strict_preview_audit.py",
        ],
        "recommended_target": "strict-preview-audit",
    },
    {
        "action_id": "public_mirror_boundary_helper",
        "priority": "P1",
        "theme": "public mirror boundary helper",
        "patterns": [
            r"public_mirror_boundary_runtime",
            r"boundary helper",
            r"assert_within_public_mirror",
            r"경계",
        ],
        "evidence_paths": [
            "ops/scripts/core/public_mirror_boundary_runtime.py",
            "tests/test_public_mirror_boundary_runtime.py",
        ],
        "recommended_target": "test-public",
    },
    {
        "action_id": "lint_uplift_plan_full_scope",
        "priority": "P1",
        "theme": "full-scope lint uplift plan",
        "patterns": [
            r"Lint uplift plan",
            r"strict-lint-inventory",
            r"lint_uplift_plan",
            r"strict-preview family",
        ],
        "evidence_paths": [
            "ops/schemas/strict-lint-inventory.schema.json",
            "ops/scripts/eval/lint_uplift_plan.py",
            "tests/test_lint_uplift_plan.py",
            "mk/eval.mk",
        ],
        "recommended_target": "lint-uplift-plan",
    },
    {
        "action_id": "type_uplift_plan_full_scope",
        "priority": "P1",
        "theme": "full-scope type uplift plan",
        "patterns": [
            r"Type uplift plan",
            r"strict-type-inventory",
            r"type_uplift_plan",
            r"allowlist.*meaning",
            r"mypy target",
        ],
        "evidence_paths": [
            "ops/schemas/strict-type-inventory.schema.json",
            "ops/scripts/eval/type_uplift_plan.py",
            "tests/test_type_uplift_plan.py",
            "mk/eval.mk",
        ],
        "recommended_target": "type-uplift-plan",
    },
    {
        "action_id": "mechanism_navigation_index",
        "priority": "P1",
        "theme": "mechanism navigation index",
        "patterns": [r"Mechanism navigation index", r"mechanism_navigation_index"],
        "evidence_paths": [
            "ops/schemas/mechanism-navigation-index.schema.json",
            "ops/scripts/mechanism/mechanism_navigation_index.py",
            "tests/test_mechanism_navigation_index.py",
        ],
        "recommended_target": "mechanism-navigation-index",
    },
    {
        "action_id": "cli_surface_inventory",
        "priority": "P1",
        "theme": "CLI surface inventory",
        "patterns": [r"CLI surface inventory", r"cli_surface_inventory", r"alias debt"],
        "evidence_paths": [
            "ops/schemas/cli-surface-inventory.schema.json",
            "ops/scripts/core/cli_surface_inventory.py",
            "tests/test_cli_surface_inventory.py",
        ],
        "recommended_target": "cli-surface-inventory",
    },
    {
        "action_id": "tools_migration_plan",
        "priority": "P1",
        "theme": "tools migration plan",
        "patterns": [r"Tools migration plan", r"tools_migration_plan", r"migration debt"],
        "evidence_paths": [
            "ops/schemas/tools-migration-plan.schema.json",
            "ops/scripts/core/tools_migration_plan.py",
            "tests/test_tools_migration_plan.py",
        ],
        "recommended_target": "tools-migration-plan",
    },
    {
        "action_id": "release_authority_inventory",
        "priority": "P1",
        "theme": "release authority inventory",
        "patterns": [r"Release authority inventory", r"release_authority_inventory"],
        "evidence_paths": [
            "ops/schemas/release-authority-inventory.schema.json",
            "ops/scripts/release/release_authority_inventory.py",
            "tests/test_release_authority_inventory.py",
        ],
        "recommended_target": "release-authority-inventory",
    },
    {
        "action_id": "observation_closeout_lint",
        "priority": "P1",
        "theme": "observation closeout lint",
        "patterns": [r"Observation closeout lint", r"observation_closeout_lint"],
        "evidence_paths": [
            "ops/schemas/observation-closeout-registry.schema.json",
            "ops/observation-closeout-registry.json",
            "ops/scripts/mechanism/observation_closeout_lint.py",
            "tests/test_observation_closeout_lint.py",
        ],
        "recommended_target": "observation-closeout-lint",
    },
    {
        "action_id": "subagent_profile_schema",
        "priority": "P1",
        "theme": "subagent profile schema and rung ladder",
        "patterns": [r"Subagent profile schema", r"subagent_profile_schema", r"rung ladder"],
        "evidence_paths": [
            "ops/schemas/subagent-profile.schema.json",
            "ops/scripts/core/subagent_profile_schema.py",
            "tests/test_subagent_profile_schema.py",
            "tests/test_select_subagent_rung_ladder.py",
        ],
        "recommended_target": "subagent-profile-schema",
    },
    {
        "action_id": "ci_tier_lane_bridge",
        "priority": "P1",
        "theme": "CI tier lane bridge",
        "patterns": [r"CI tier lane bridge", r"ci_tier_lane_bridge", r"lane_ci_steps", r"pack_ci_steps"],
        "evidence_paths": [
            "ops/schemas/ci-tier-lane-bridge.schema.json",
            "ops/scripts/test/ci_tier_lane_bridge.py",
            "tests/test_ci_tier_lane_bridge.py",
        ],
        "recommended_target": "ci-tier-lane-bridge",
    },
    {
        "action_id": "compatibility_alias_deprecation",
        "priority": "P1",
        "theme": "compatibility alias deprecation inventory",
        "patterns": [r"Compatibility alias deprecation", r"compatibility_alias_deprecation", r"flat alias"],
        "evidence_paths": [
            "ops/schemas/compatibility-alias-deprecation.schema.json",
            "ops/scripts/core/compatibility_alias_deprecation.py",
            "tests/test_compatibility_alias_deprecation.py",
        ],
        "recommended_target": "compatibility-alias-deprecation",
    },
    {
        "action_id": "public_surface_snapshot",
        "priority": "P1",
        "theme": "public surface snapshot",
        "patterns": [r"Public surface snapshot", r"public_surface_snapshot", r"iter_public_files"],
        "evidence_paths": [
            "ops/schemas/public-surface-snapshot.schema.json",
            "ops/scripts/public/public_surface_snapshot.py",
            "tests/test_public_surface_snapshot.py",
        ],
        "recommended_target": "public-surface-snapshot",
    },
    {
        "action_id": "doc_graph_integrity_lint",
        "priority": "P1",
        "theme": "doc graph integrity lint",
        "patterns": [r"Doc graph integrity", r"doc_graph_integrity", r"doc-graph-orphan"],
        "evidence_paths": [
            "ops/schemas/doc-graph-integrity.schema.json",
            "ops/doc-graph-orphan-allowlist.json",
            "ops/scripts/eval/doc_graph_integrity.py",
            "tests/test_doc_graph_integrity.py",
        ],
        "recommended_target": "doc-graph-integrity",
    },
    {
        "action_id": "release_lane_mutability_split",
        "priority": "P0",
        "theme": "release lane mutability split",
        "patterns": [
            r"lane mutability",
            r"release-evidence-converge",
            r"release-verify-current",
            r"release-sealed-verify",
            r"Generate once in converge lane",
            r"Verify without writing in current lane",
        ],
        "evidence_paths": [
            "mk/release.mk",
            "ops/scripts/release/release_workflow_order_guard.py",
            "tests/test_makefile_static_gates.py",
        ],
        "recommended_target": "release-evidence-converge",
    },
    {
        "action_id": "sealed_summary_vocabulary_demotion",
        "priority": "P0",
        "theme": "sealed summary vocabulary demotion",
        "patterns": [
            r"pre_distribution_package_binding_status",
            r"source_closeout_distribution_binding_status",
            r"sealed_release_status.*pre[- ]distribution",
            r"source closeout.*sealed",
            r"field rename/demotion",
        ],
        "evidence_paths": [
            "ops/scripts/release/release_closeout_summary.py",
            "ops/schemas/release-closeout-summary.schema.json",
            "tests/test_release_closeout_summary.py",
            "tests/test_release_status_v2.py",
        ],
        "recommended_target": "release-closeout-summary-report",
    },
    {
        "action_id": "selector_marker_scope_parity",
        "priority": "P1",
        "theme": "explicit selector and marker-wide lane parity",
        "patterns": [
            r"marker-wide",
            r"marker expression",
            r"explicit selector",
            r"test-release-sealing-core",
            r"test-report-contract-core",
            r"RELEASE_SEALING_TESTS",
            r"REPORT_CONTRACT_CORE_TESTS",
        ],
        "evidence_paths": [
            "mk/test.mk",
            "ops/test-lane-registry.json",
            "tests/test_makefile_static_gates.py",
        ],
        "recommended_target": "test-release-sealing-all",
    },
    {
        "action_id": "source_package_distribution_binding",
        "priority": "P0",
        "theme": "source package and distribution ZIP binding",
        "patterns": [r"source package", r"source ZIP", r"distribution ZIP", r"archive profile", r"package mode"],
        "evidence_paths": [
            "ops/reports/source-package-clean-extract.json",
            "ops/reports/release-smoke-report.json",
            "external-reports/report-reference-manifest.json",
        ],
        "recommended_target": "release-source-package-check",
    },
    {
        "action_id": "release_evidence_bundle_and_attestation",
        "priority": "P1",
        "theme": "release evidence bundle and attestation",
        "patterns": [
            r"evidence bundle",
            r"attestation",
            r"post-seal",
            r"audit pack",
            r"release[- ]evidence",
            r"release-closeout-batch-manifest",
            r"batch-manifest",
            r"finality",
            r"closeout self-check",
        ],
        "evidence_paths": [
            "ops/reports/release-closeout-finality-attestation.json",
            "ops/reports/release-closeout-batch-manifest.json",
        ],
        "recommended_target": "release-evidence-closeout-sealed-dry-run",
    },
    {
        "action_id": "full_suite_evidence_currentness",
        "priority": "P1",
        "theme": "full-suite evidence currentness",
        "patterns": [r"full-suite", r"full suite", r"test-execution-summary-full", r"collect-only", r"nodeid"],
        "evidence_paths": ["ops/reports/test-execution-summary-full.json"],
        "recommended_target": "test-execution-summary-full-refresh",
    },
    {
        "action_id": "promotion_truth_ladder",
        "priority": "P0",
        "theme": "live gate and promotion truth ladder",
        "patterns": [r"truth ladder", r"live gate", r"promotion_blockers", r"can_promote_result", r"machine_release"],
        "evidence_paths": [
            "ops/reports/auto-improve-readiness.json",
            "ops/reports/release-closeout-summary.json",
            "ops/reports/release-evidence-dashboard.json",
        ],
        "recommended_target": "auto-improve-readiness-report",
    },
    {
        "action_id": "goal_contract_schema",
        "priority": "P0",
        "theme": "goal contract schema for long-running auto-improve",
        "patterns": [
            r"goal contract",
            r"codex-goal-contract",
            r"GoalSpec",
            r"required_evidence",
            r"stop_conditions",
        ],
        "evidence_paths": [
            "ops/schemas/codex-goal-contract.schema.json",
            "ops/reports/codex-goal-contract.json",
            "tests/test_codex_goal_contract.py",
        ],
        "recommended_target": "codex-goal-contract",
    },
    {
        "action_id": "codex_goal_adapter",
        "priority": "P0",
        "theme": "local set_goal adapter and backend detection",
        "patterns": [
            r"set_goal",
            r"get_goal",
            r"update_goal",
            r"GoalBackend",
            r"feature detection",
            r"thread/goal",
            r"app-server",
        ],
        "evidence_paths": [
            "ops/scripts/core/codex_goal_client.py",
            "ops/reports/codex-goal-contract.json",
            "tests/test_codex_goal_client.py",
        ],
        "recommended_target": "codex-goal-client",
    },
    {
        "action_id": "codex_goal_prompt_generator",
        "priority": "P0",
        "theme": "goal prompt generator with promotion ban wording",
        "patterns": [
            r"goal prompt",
            r"codex_goal_prompt",
            r"can_promote_result=false",
            r"promotion forbidden",
            r"promotion ban",
        ],
        "evidence_paths": [
            "ops/scripts/mechanism/codex_goal_prompt.py",
            "ops/schemas/codex-goal-prompt.schema.json",
            "ops/reports/codex-goal-prompt.json",
            "tests/test_codex_goal_prompt.py",
        ],
        "recommended_target": "codex-goal-prompt",
    },
    {
        "action_id": "auto_improve_goal_contract_input",
        "priority": "P0",
        "theme": "auto-improve loop goal contract input and budget ceiling",
        "patterns": [
            r"--goal-contract",
            r"auto_improve_loop",
            r"policy/CLI.*larger budget",
            r"larger budget",
            r"contract digest",
            r"time_budget_exhausted",
            r"proposal_budget_exhausted",
        ],
        "evidence_paths": [
            "ops/scripts/mechanism/auto_improve_loop.py",
            "ops/scripts/mechanism/auto_improve_runtime.py",
            "ops/reports/codex-goal-contract.json",
            "tests/test_auto_improve_runtime.py",
        ],
        "recommended_target": "codex-goal-client",
    },
    {
        "action_id": "goal_run_status_audit_resume",
        "priority": "P0",
        "theme": "goal run status, audit log, checkpoint, and resume contract",
        "patterns": [
            r"goal-run-status",
            r"audit-log",
            r"checkpoint",
            r"resume",
            r"run id",
            r"run_ids",
            r"session_id",
            r"session identity",
            r"status\.md",
            r"resume_from_checkpoint",
            r"--goal-contract",
            r"--resume-from-checkpoint",
        ],
        "evidence_paths": [
            "ops/schemas/goal-run-status.schema.json",
            "ops/scripts/mechanism/auto_improve_loop.py",
            "ops/scripts/mechanism/goal_run_status.py",
            "ops/scripts/mechanism/goal_runtime_runner.py",
            "ops/reports/goal-run-status.json",
            "tests/test_goal_auto_improve_runtime.py",
            "tests/test_goal_run_status.py",
            "tests/test_goal_runtime_runner.py",
        ],
        "recommended_target": "auto-improve-goal-run",
    },
    {
        "action_id": "goal_execution_runtime_certificate",
        "priority": "P0",
        "theme": "bounded goal execution runtime certificate",
        "patterns": [
            r"runtime certificate",
            r"self-improvement loop",
            r"자가개선 루프",
            r"full gate",
            r"source-package",
            r"public-check",
            r"bounded trial",
        ],
        "evidence_paths": [
            "mk/mechanism.mk",
            "ops/reports/goal-runtime-certificate.json",
            "ops/schemas/codex-goal-contract.schema.json",
            "ops/scripts/mechanism/goal_run_status.py",
            "ops/scripts/mechanism/goal_runtime_certificate_report.py",
            "ops/scripts/mechanism/goal_runtime_certificate.py",
            "tests/test_goal_runtime_certificate.py",
            "tests/test_goal_run_status.py",
        ],
        "recommended_target": "goal-runtime-certificate",
    },
    {
        "action_id": "command_heartbeat_observability",
        "priority": "P1",
        "theme": "long command heartbeat and quiet-run observability",
        "patterns": [
            r"heartbeat",
            r"last_stdout_at",
            r"last_stderr_at",
            r"last_artifact_touch_at",
            r"quiet_seconds",
            r"time_budget_exhausted",
        ],
        "evidence_paths": [
            "ops/scripts/core/command_runtime.py",
            "ops/schemas/executor-report.schema.json",
            "ops/scripts/core/source_package_clean_extract.py",
            "ops/schemas/source-package-clean-extract.schema.json",
            "ops/reports/source-package-clean-extract.json",
            "tests/test_command_runtime_heartbeat.py",
            "tests/test_source_package_clean_extract.py",
        ],
        "recommended_target": "test-subprocess",
    },
    {
        "action_id": "goal_executor_backoff_observability",
        "priority": "P1",
        "theme": "goal executor retry-after backoff and status observability",
        "patterns": [
            r"executor backoff",
            r"retry-after",
            r"retry_after",
            r"usage limit",
            r"executor_usage_limited",
            r"backoff.*heartbeat",
        ],
        "evidence_paths": [
            "ops/scripts/mechanism/goal_runtime_backoff.py",
            "ops/scripts/mechanism/goal_runtime_runner.py",
            "ops/reports/goal-run-status.json",
            "ops/schemas/goal-run-status.schema.json",
            "tests/test_goal_runtime_runner.py",
            "tests/test_goal_run_status.py",
        ],
        "recommended_target": "auto-improve-goal-run",
    },
    {
        "action_id": "selected_contract_currentness_gate",
        "priority": "P0",
        "theme": "selected contract currentness gate distinct from artifact freshness",
        "patterns": [
            r"selected contract",
            r"selected_contract_currentness",
            r"test_execution_summary_contract_drift",
            r"artifact freshness pass",
            r"operational currentness drift",
        ],
        "evidence_paths": [
            "ops/scripts/mechanism/auto_improve_readiness_release_authority_runtime.py",
            "ops/reports/auto-improve-readiness.json",
            "ops/reports/test-execution-summary.json",
            "tests/test_auto_improve_readiness_release_authority_runtime.py",
        ],
        "recommended_target": "auto-improve-readiness-report",
    },
    {
        "action_id": "sealed_preflight_canonicalization",
        "priority": "P0",
        "theme": "sealed authority preflight clean-required canonical evidence",
        "patterns": [
            r"sealed preflight",
            r"release authority",
            r"expected blocked",
            r"clean-required",
            r"sealed authority clean",
            r"binding_pass_authority_blocked",
        ],
        "evidence_paths": [
            "mk/release.mk",
            "ops/scripts/mechanism/auto_improve_readiness_constants_runtime.py",
            "ops/reports/release-closeout-sealed-rehearsal-check.json",
            "ops/scripts/release/release_closeout_sealed_rehearsal_check.py",
            "ops/schemas/release-closeout-sealed-rehearsal-check.schema.json",
            "tests/test_release_closeout_sealed_rehearsal_check.py",
            "tests/test_auto_improve_readiness_runtime.py",
            "tests/test_makefile_static_gates.py",
        ],
        "recommended_target": "release-authority-sealed-preflight",
    },
    {
        "action_id": "negative_learning_ledger",
        "priority": "P2",
        "theme": "standalone negative learning ledger",
        "patterns": [
            r"negative learning",
            r"negative lessons",
            r"self-improvement-negative-lessons",
            r"same failure",
        ],
        "evidence_paths": [
            "ops/schemas/self-improvement-negative-lessons.schema.json",
            "ops/reports/self-improvement-negative-lessons.json",
            "tests/test_self_improvement_negative_lessons.py",
        ],
        "recommended_target": "self-improvement-negative-lessons",
    },
    {
        "action_id": "remediation_backlog",
        "priority": "P1",
        "theme": "remediation backlog for repeated blockers",
        "patterns": [
            r"remediation backlog",
            r"remediation-backlog",
            r"repeated blocker",
            r"blocked.*backlog",
        ],
        "evidence_paths": [
            "ops/schemas/remediation-backlog.schema.json",
            "ops/reports/remediation-backlog.json",
            "tests/test_remediation_backlog.py",
        ],
        "recommended_target": "remediation-backlog",
    },
    {
        "action_id": "git_worktree_goal_guard",
        "priority": "P1",
        "theme": "Git worktree and ZIP mode guard for long goal runs",
        "patterns": [
            r"Git worktree",
            r"ZIP extraction mode",
            r"trial only",
            r"report-only",
            r"long_run_allowed",
            r"git rev-parse",
            r"worktree path",
            r"private repo",
        ],
        "evidence_paths": [
            "mk/mechanism.mk",
            "ops/scripts/mechanism/goal_worktree_guard.py",
            "ops/schemas/goal-worktree-guard.schema.json",
            "tests/test_goal_worktree_guard.py",
        ],
        "recommended_target": "auto-improve-goal-preflight",
    },
    {
        "action_id": "goal_runtime_transient_cleanup_gate",
        "priority": "P1",
        "theme": "pre-run cleanup and admission gate for long goal runs",
        "patterns": [
            r"transient artifact cleanup",
            r"transient cleanup gate",
            r"goal-runtime-clean-transient",
            r"goal-runtime-run-admission",
            r"goal-runtime-run-admission-local-refresh",
            r"long-run-preflight-clean",
            r"runnable proposal",
            r"fixed-point",
            r"run-local evidence",
            r"obsolete tracked goal",
            r"stale legacy runtime",
        ],
        "evidence_paths": [
            "mk/mechanism.mk",
            "ops/scripts/mechanism/goal_runtime_clean_transient.py",
            "ops/schemas/goal-runtime-clean-transient.schema.json",
            "tests/test_goal_runtime_clean_transient.py",
            "ops/scripts/mechanism/goal_runtime_quarantine_preflight.py",
            "ops/schemas/goal-runtime-quarantine-preflight.schema.json",
            "tests/test_goal_runtime_quarantine_preflight.py",
            "ops/scripts/mechanism/goal_runtime_run_admission.py",
            "ops/schemas/goal-runtime-run-admission.schema.json",
            "tests/test_goal_runtime_run_admission.py",
        ],
        "recommended_target": "goal-runtime-run-admission",
    },
    {
        "action_id": "artifact_freshness_performance_observability",
        "priority": "P0",
        "theme": "artifact freshness performance and long-gate observability",
        "patterns": [
            r"artifact freshness",
            r"schema validator cache",
            r"validator cache",
            r"progress jsonl",
            r"per-phase timing",
            r"check-observed",
            r"incremental --changed-only",
            r"long-running gate",
        ],
        "evidence_paths": [
            "ops/scripts/core/artifact_freshness_runtime.py",
            "ops/reports/artifact-freshness-report.json",
            "tests/test_artifact_freshness_runtime.py",
            "mk/artifact.mk",
        ],
        "recommended_target": "artifact-freshness-check",
    },
    {
        "action_id": "repo_boundary_history_hygiene",
        "priority": "P0",
        "theme": "private vault and public/dev repo boundary hygiene",
        "patterns": [
            r"repo boundary",
            r"vault/code",
            r"public/dev repo",
            r"private vault",
            r"public mirror",
            r"raw/runs/archive",
            r"generated bulk",
        ],
        "evidence_paths": [
            ".gitignore",
            "ARCHITECTURE.md",
            "docs/public-mirror.md",
            "ops/scripts/public/public_surface_policy.py",
            "tests/test_public_surface_policy.py",
            "tests/test_export_public_repo.py",
            "ops/reports/public-check-summary.json",
        ],
        "recommended_target": "public-check",
    },
    {
        "action_id": "github_native_security_automation",
        "priority": "P0",
        "theme": "GitHub-native security and workflow governance",
        "patterns": [
            r"Dependabot",
            r"CodeQL",
            r"dependency review",
            r"required status",
            r"action pinning",
            r"concurrency",
            r"GitHub-native",
        ],
        "evidence_paths": [
            ".github/workflows/ci.yml",
            ".github/workflows/release.yml",
            ".github/dependabot.yml",
            ".github/workflows/codeql.yml",
            ".github/workflows/dependency-review.yml",
        ],
        "recommended_target": "github-security-automation",
    },
    {
        "action_id": "maintainability_hotspot_refactor_backlog",
        "priority": "P1",
        "theme": "complexity hotspot and giant test decomposition",
        "patterns": [
            r"complexity hotspot",
            r"giant test",
            r"fixture cache",
            r"function budget",
            r"orchestrator",
            r"hotspot refactor",
        ],
        "evidence_paths": [
            "ops/reports/function-budget-refactor-proposals.json",
            "tests/test_function_budget_refactor_proposals.py",
            "ops/scripts/eval/function_budget_refactor_proposals.py",
        ],
        "recommended_target": "function-budget-refactor-proposals",
    },
    {
        "action_id": "generated_artifact_tracking_policy",
        "priority": "P1",
        "theme": "generated artifact tracking and churn policy",
        "patterns": [
            r"generated artifact",
            r"commit churn",
            r"decision-grade",
            r"ephemeral",
            r"tracked set",
            r"canonical refresh",
        ],
        "evidence_paths": [
            "ops/reports/generated-artifact-index.json",
            "ops/scripts/core/generated_artifact_index.py",
            "ops/schemas/generated-artifact-index.schema.json",
            "tests/test_generated_artifact_index.py",
        ],
        "recommended_target": "generated-artifact-index",
    },
    {
        "action_id": "public_export_negative_assertions",
        "priority": "P2",
        "theme": "public/private export negative assertions",
        "patterns": [
            r"negative assertion",
            r"excluded_prefix_absence",
            r"private_pattern_absence",
            r"local_path_absence",
            r"public export",
            r"public/private boundary",
        ],
        "evidence_paths": [
            "ops/scripts/public/export_public_repo.py",
            "ops/scripts/public/public_check_summary.py",
            "tests/test_export_public_repo.py",
            "tests/test_public_check_summary.py",
            "ops/reports/public-check-summary.json",
        ],
        "recommended_target": "public-check",
    },
    {
        "action_id": "repository_surface_entrypoint_documentation",
        "priority": "P2",
        "theme": "full-vault, public export, and release source ZIP entrypoint documentation",
        "patterns": [
            r"repository-surfaces",
            r"full-vault",
            r"full vault",
            r"public export",
            r"release source zip",
            r"source ZIP",
            r"세\s*표면",
        ],
        "evidence_paths": [
            "docs/repository-surfaces.md",
            "docs/README.md",
            "README.md",
            "ARCHITECTURE.md",
            "docs/public-mirror.md",
            "docs/release.md",
            "tests/test_doc_graph_integrity.py",
        ],
        "recommended_target": "doc-graph-integrity",
    },
    {
        "action_id": "release_mechanism_service_layer_extraction",
        "priority": "P2",
        "theme": "release and mechanism service-layer extraction",
        "patterns": [
            r"service layer",
            r"runtime service",
            r"release/mechanism",
            r"authority.*currentness.*risk.*learning_claim",
            r"JSON payload assembly",
            r"domain decision logic",
        ],
        "evidence_paths": [
            "ops/scripts/core/release_authority_state_runtime.py",
            "ops/scripts/core/release_currentness_state_runtime.py",
            "ops/scripts/core/release_risk_state_runtime.py",
            "ops/scripts/core/learning_claim_state_runtime.py",
            "ops/scripts/release/release_status_v2.py",
            "ops/scripts/mechanism/auto_improve_readiness_release_authority_runtime.py",
            "ops/scripts/release/external_report_lifecycle_runtime.py",
            "ops/scripts/release/release_authority_inventory.py",
            "ops/scripts/release/release_evidence_cohort.py",
            "ops/scripts/release/release_evidence_dashboard.py",
            "ops/scripts/release/release_closeout_summary.py",
            "ops/scripts/release/release_clean_blocker_ledger.py",
            "ops/scripts/learning/learning_delta_scoreboard_unlock_runtime.py",
            "tests/test_release_authority_state_runtime.py",
            "tests/test_release_currentness_state_runtime.py",
            "tests/test_release_risk_state_runtime.py",
            "tests/test_learning_claim_state_runtime.py",
            "tests/test_release_status_v2.py",
        ],
        "recommended_target": "release-authority-inventory",
    },
    {
        "action_id": "supply_chain_external_verification",
        "priority": "P2",
        "theme": "external supply-chain verification",
        "patterns": [
            r"Scorecard",
            r"SBOM schema validation",
            r"SLSA",
            r"in-toto verification",
            r"supply-chain external verification",
            r"provenance verification",
        ],
        "evidence_paths": [
            "ops/reports/supply-chain-gate-report.json",
            "ops/reports/sbom-readiness-gate-report.json",
            "ops/reports/in-toto-statement.json",
            "ops/reports/sigstore-bundle-verification.json",
            "mk/supply_chain.mk",
            ".github/workflows/release.yml",
            ".github/workflows/dependency-review.yml",
        ],
        "recommended_target": "supply-chain-check",
    },
    {
        "action_id": "github_governance_live_drift_verification",
        "priority": "P2",
        "theme": "live GitHub governance drift verification",
        "patterns": [
            r"branch protection",
            r"ruleset",
            r"required checks",
            r"live GitHub governance",
            r"governance drift",
            r"live drift",
        ],
        "evidence_paths": [
            ".github/release-governance.yml",
            "ops/reports/github-governance-live-drift.json",
        ],
        "recommended_target": "collaboration-governance",
    },
    {
        "action_id": "collaboration_governance_surface",
        "priority": "P2",
        "theme": "collaboration governance surface",
        "patterns": [
            r"CODEOWNERS",
            r"PR template",
            r"commit taxonomy",
            r"collaboration governance",
        ],
        "evidence_paths": [
            ".github/CODEOWNERS",
            ".github/pull_request_template.md",
            "CONTRIBUTING.md",
        ],
        "recommended_target": "collaboration-governance",
    },
]

ALL_EVIDENCE_OR_PLANNED_ACTION_IDS = {
    "script_output_surfaces_currentness",
    "function_budget_proposal_adapter",
    "windows_path_and_archive_alias_parity",
}

IMPLEMENTED_ARTIFACT_ACTIONS = {
    "negative_learning_ledger": (
        "ops/reports/self-improvement-negative-lessons.json",
        "self_improvement_negative_lessons",
    ),
    "remediation_backlog": (
        "ops/reports/remediation-backlog.json",
        "remediation_backlog",
    ),
}

SPRINT_PRIORITIES: dict[str, str] = {
    "source_package_distribution_binding": "P0",
    "full_suite_evidence_currentness": "P0",
    "promotion_truth_ladder": "P0",
    "goal_execution_runtime_certificate": "P0",
    "artifact_freshness_performance_observability": "P0",
    "maintainability_hotspot_refactor_backlog": "P0",
    "release_evidence_bundle_and_attestation": "P1",
    "goal_contract_schema": "P1",
    "codex_goal_adapter": "P1",
    "codex_goal_prompt_generator": "P1",
    "auto_improve_goal_contract_input": "P1",
    "goal_run_status_audit_resume": "P1",
    "goal_executor_backoff_observability": "P1",
    "function_budget_proposal_adapter": "P1",
    "supply_chain_external_verification": "P2",
    "outcome_provenance_gate_policy": "P2",
}
