from __future__ import annotations

from ops.scripts.core import release_authority_state_runtime as _state

RELEASE_READINESS_STATE_FALLBACK_VALUES = _state.RELEASE_READINESS_STATE_FALLBACK_VALUES
STATUS_V2_AXIS_FIELDS = _state.STATUS_V2_AXIS_FIELDS
STATUS_V2_MIGRATION_READINESS_STATUS = _state.STATUS_V2_MIGRATION_READINESS_STATUS
STATUS_V2_RECOMMENDED_CONSUMER_FIELDS = _state.STATUS_V2_RECOMMENDED_CONSUMER_FIELDS
STATUS_V2_SCHEMA_VERSION = _state.STATUS_V2_SCHEMA_VERSION
decide_legacy_strict_clean_sealed_status = _state.decide_legacy_strict_clean_sealed_status
decide_sealed_release_status = _state.decide_sealed_release_status
release_status_v2_payload = _state.release_status_v2_payload
release_status_v2_view = _state.release_status_v2_view
release_status_v2_view_with_readiness_fallback = _state.release_status_v2_view_with_readiness_fallback
