from __future__ import annotations

import argparse
from pathlib import Path

from ops.scripts.test.test_lane_registry_runtime import (
    load_registry,
    pack_effective_selectors,
    pack_mark_expr,
    pack_selectors,
)

GENERATED_HEADER = """# Generated by: python -m ops.scripts.test.generate_test_mk_selectors
# Source of truth: ops/test-lane-registry.json
# Regenerate with: make test-selectors-sync
"""

PACK_VARIABLES: dict[str, str] = {
    "fast_smoke": "FAST_SMOKE_TESTS",
    "default_test_boundary": "DEFAULT_TEST_BOUNDARY_TESTS",
    "runtime_hotspot_smoke": "RUNTIME_HOTSPOT_SMOKE_TESTS",
    "schema_static_smoke": "SCHEMA_STATIC_SMOKE_TESTS",
    "report_contract_core": "REPORT_CONTRACT_CORE_TESTS",
    "report_contract_all": "REPORT_CONTRACT_ALL_TESTS",
    "release_sealing_core": "RELEASE_SEALING_CORE_TESTS",
    "subprocess_checks": "SUBPROCESS_TESTS",
    "release_closeout_regression": "RELEASE_CLOSEOUT_REGRESSION_TESTS",
}

# Hybrid packs prepend a Make-owned marker expression before explicit selectors.
PACK_MARK_EXPR_MAKE_VARIABLES: dict[str, str] = {
    "report_contract_all": "PYTEST_REPORT_CONTRACT_MARK_EXPR",
}

DERIVED_ALIASES: dict[str, str] = {
    "REPORT_CONTRACT_TESTS": "$(REPORT_CONTRACT_CORE_TESTS)",
    "RELEASE_SEALING_TESTS": "$(RELEASE_SEALING_CORE_TESTS)",
}


def _format_selector_variable(
    variable: str,
    selectors: tuple[str, ...],
    *,
    prefix: str = "",
) -> str:
    if not selectors and not prefix:
        return f"{variable} ?="
    lines = [f"{variable} ?= {prefix}"] if prefix else [f"{variable} ?= \\"]
    for selector in selectors:
        lines.append(f"\t{selector} \\")
    if lines[-1].endswith(" \\"):
        lines[-1] = lines[-1][:-2]
    return "\n".join(lines)


def render_test_selectors_mk(vault: Path) -> str:
    registry = load_registry(vault)
    blocks: list[str] = [GENERATED_HEADER.rstrip()]

    for pack_id, variable in PACK_VARIABLES.items():
        mark_expr_variable = PACK_MARK_EXPR_MAKE_VARIABLES.get(pack_id)
        mark_expr = pack_mark_expr(registry, pack_id)
        if mark_expr_variable is not None or mark_expr:
            selectors = pack_effective_selectors(registry, pack_id, vault=vault)
        else:
            selectors = pack_selectors(registry, pack_id)
        if mark_expr_variable is not None:
            registry_mark_expr = pack_mark_expr(registry, pack_id)
            if not registry_mark_expr:
                raise SystemExit(
                    f"{pack_id} requires pytest_mark_expr in ops/test-lane-registry.json"
                )
            prefix = f'-m "$({mark_expr_variable})" \\'
            blocks.append(_format_selector_variable(variable, selectors, prefix=prefix))
        else:
            blocks.append(_format_selector_variable(variable, selectors))
        blocks.append("")

    for variable, value in DERIVED_ALIASES.items():
        blocks.append(f"{variable} ?= {value}")
        blocks.append("")

    return "\n".join(blocks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate mk/test-selectors.generated.mk from registry.")
    parser.add_argument("--vault", type=Path, default=Path())
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("mk/test-selectors.generated.mk"),
        help="Output makefile fragment path.",
    )
    parser.add_argument("--check", action="store_true", help="Fail if output would change.")
    args = parser.parse_args()

    rendered = render_test_selectors_mk(args.vault.resolve())
    out_path = (args.vault / args.out).resolve()
    if args.check:
        current = out_path.read_text(encoding="utf-8") if out_path.is_file() else ""
        if current != rendered:
            raise SystemExit(f"{out_path} is stale; run make test-selectors-sync")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
